### PR TITLE
Making the global search functional

### PR DESCRIPTION
**Pull request by nfoert**
For #130 

- [x] Search
    - [x] Case Sensitive
    - [x] Case Insensitive
    - [x] Match Word
    - [x] Regex
- [x] Replace
    - [x] Replace all
- [x] Fix layout

### CODE REVIEW

**Comment by billyeatcookies** [comment]
@nfoert the button click events of ButtonsEntry don't have to be done like that, instead just pass in the tuples of format `(icon_name, callback)`. 

Also, the layout error was caused by the `container` used by search-replace bars set to `expand=True`

**Comment by nfoert** [comment]
Thanks for the changes @billyeatcookies. The click events for `ButtonsEntry` makes sense, I haven't had a ton of experience with tkinter.

**Comment by nfoert** [comment]
Hi @billyeatcookies, I just got the replace functionality to work. I'm not sure we need to implement match case replace though. The replace works by looking at the results of the search and just replacing what was found when searching with what you put in the replace text box. I don't really see how match case replace would be helpful when you could just do a match case search, unless I'm not understanding it correctly.
Thanks.

**Comment by billyeatcookies** [comment]
@nfoert the preserve case option is not that important actually, the main idea was to fully capitalize the replacing word if the found word is fully capitalized. second case would be first letter capped words, those can be replaced as first letter capped with the preserve case option. So we can ignore that part :)

Also I just changed some docstring stylings, etc xd

**Comment by billyeatcookies** [comment]
- [ ] Scrolling seems to only happen sometimes (line 50 in `results.py`)

I'll move this to a new separate issue for now, we can resolve it later!

**Comment by nfoert** [comment]
Sounds good, thanks @billyeatcookies!

**Comment by billyeatcookies** [comment]
thanks alot for the awesome contribution! ❤

**Pull request merged**
